# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba04dd390f9e37084b3d0e3c5620afcb"
name = "repots"
handle = "repots"
application_url = "https://big-due-adjustment-companies.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "r-t-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://big-due-adjustment-companies.trycloudflare.com/auth/callback",
  "https://big-due-adjustment-companies.trycloudflare.com/auth/shopify/callback",
  "https://big-due-adjustment-companies.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[web]
proxy_url = "https://infringement-learn-paraguay-robot.trycloudflare.com"

  [[web.proxy]]
  prefix = "/apps/discounts"
  destination = "/api/discounts"

[pos]
embedded = false
