# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration


client_id = "256a5609d48f6540443ac393520d1810"
name = "b2b-quote"
handle = "b2b-quote"
application_url = "https://app.promoforbusiness.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "promoforbusiness.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_discounts,write_discounts_allocator_functions,write_orders,write_products"

[auth]
redirect_urls = [
  "https://app.promoforbusiness.com/auth/callback",
  "https://app.promoforbusiness.com/auth/shopify/callback",
  "https://app.promoforbusiness.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[web]
proxy_url = "https://app.promoforbusiness.com"

  [[web.proxy]]
  prefix = "/apps/discounts"
  destination = "/api/discounts"


[pos]
embedded = false

